### ISSUE TITLE
Branch Not Possible

### ISSUE THREAD

**Issue by daniel-frisch-kit** [tuckermcclure/matlab-plot-big#1]
Hello, I tried to make the change that defines 'DeletePlot' as Nested Function. That would be my first pull request. If I understand it right, I first have to make a branch, do my changes and then I can send you the pull request. However the blue "Create Branch" button doesn't appear in your matlab-plot-big project - it says "Nothing to show" (see screenshot). In my test project I can create new branches. 

![image](https://cloud.githubusercontent.com/assets/22419910/20385572/3298eade-acb8-11e6-8ca7-323a77daf28d.png)

**Comment by tuckermcclure** [comment]
Hi @daniel-frisch-kit! I'm sorry I'm only just seeing your issue. I had my GitHub settings messed up and never received a notification. Thanks for your message.

You'll need to _fork_ this repository, and then you can work on your own fork however you like (e.g., making a branch). When it works on your end and is ready to rejoin the main project, you open a Pull Request from your fork into this repository. There's more about this process here:

https://help.github.com/articles/fork-a-repo/

Again, sorry I missed this!
